package com.zxh.ssm.module.whole.mapper;

import com.zxh.ssm.module.whole.pojo.UserDetails;
import com.zxh.ssm.module.whole.pojo.UserDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbggenerated
     */
    int countByExample(UserDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbggenerated
     */
    int deleteByExample(UserDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbggenerated
     */
    int insert(UserDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbggenerated
     */
    int insertSelective(UserDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbggenerated
     */
    List<UserDetails> selectByExample(UserDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbggenerated
     */
    UserDetails selectByPrimaryKey(String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserDetails record, @Param("example") UserDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserDetails record, @Param("example") UserDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserDetails record);
}