package com.zxh.ssm.module.whole.pojo;

import java.util.Date;

public class UserDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.isPassed
     *
     * @mbggenerated
     */
    private String ispassed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.realName
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.telephone
     *
     * @mbggenerated
     */
    private Integer telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.submitDate
     *
     * @mbggenerated
     */
    private Date submitdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.passDate
     *
     * @mbggenerated
     */
    private Date passdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.allowedBy
     *
     * @mbggenerated
     */
    private String allowedby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.email
     *
     * @return the value of user_details.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.email
     *
     * @param email the value for user_details.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.isPassed
     *
     * @return the value of user_details.isPassed
     *
     * @mbggenerated
     */
    public String getIspassed() {
        return ispassed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.isPassed
     *
     * @param ispassed the value for user_details.isPassed
     *
     * @mbggenerated
     */
    public void setIspassed(String ispassed) {
        this.ispassed = ispassed == null ? null : ispassed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.userName
     *
     * @return the value of user_details.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.userName
     *
     * @param username the value for user_details.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.password
     *
     * @return the value of user_details.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.password
     *
     * @param password the value for user_details.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.realName
     *
     * @return the value of user_details.realName
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.realName
     *
     * @param realname the value for user_details.realName
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.sex
     *
     * @return the value of user_details.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.sex
     *
     * @param sex the value for user_details.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.telephone
     *
     * @return the value of user_details.telephone
     *
     * @mbggenerated
     */
    public Integer getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.telephone
     *
     * @param telephone the value for user_details.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(Integer telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.birthday
     *
     * @return the value of user_details.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.birthday
     *
     * @param birthday the value for user_details.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.submitDate
     *
     * @return the value of user_details.submitDate
     *
     * @mbggenerated
     */
    public Date getSubmitdate() {
        return submitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.submitDate
     *
     * @param submitdate the value for user_details.submitDate
     *
     * @mbggenerated
     */
    public void setSubmitdate(Date submitdate) {
        this.submitdate = submitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.passDate
     *
     * @return the value of user_details.passDate
     *
     * @mbggenerated
     */
    public Date getPassdate() {
        return passdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.passDate
     *
     * @param passdate the value for user_details.passDate
     *
     * @mbggenerated
     */
    public void setPassdate(Date passdate) {
        this.passdate = passdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.allowedBy
     *
     * @return the value of user_details.allowedBy
     *
     * @mbggenerated
     */
    public String getAllowedby() {
        return allowedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.allowedBy
     *
     * @param allowedby the value for user_details.allowedBy
     *
     * @mbggenerated
     */
    public void setAllowedby(String allowedby) {
        this.allowedby = allowedby == null ? null : allowedby.trim();
    }
}