package com.zxh.ssm.module.whole.pojo;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userEmail
     *
     * @mbggenerated
     */
    private String useremail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userPassword
     *
     * @mbggenerated
     */
    private String userpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userRealName
     *
     * @mbggenerated
     */
    private String userrealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userPhone
     *
     * @mbggenerated
     */
    private String userphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userUnit
     *
     * @mbggenerated
     */
    private String userunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.reviewStatus
     *
     * @mbggenerated
     */
    private String reviewstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.perissionInformation
     *
     * @mbggenerated
     */
    private String perissioninformation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.joinDate
     *
     * @mbggenerated
     */
    private Date joindate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userEmail
     *
     * @return the value of user.userEmail
     *
     * @mbggenerated
     */
    public String getUseremail() {
        return useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userEmail
     *
     * @param useremail the value for user.userEmail
     *
     * @mbggenerated
     */
    public void setUseremail(String useremail) {
        this.useremail = useremail == null ? null : useremail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userName
     *
     * @return the value of user.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userName
     *
     * @param username the value for user.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userPassword
     *
     * @return the value of user.userPassword
     *
     * @mbggenerated
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userPassword
     *
     * @param userpassword the value for user.userPassword
     *
     * @mbggenerated
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword == null ? null : userpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userRealName
     *
     * @return the value of user.userRealName
     *
     * @mbggenerated
     */
    public String getUserrealname() {
        return userrealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userRealName
     *
     * @param userrealname the value for user.userRealName
     *
     * @mbggenerated
     */
    public void setUserrealname(String userrealname) {
        this.userrealname = userrealname == null ? null : userrealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userPhone
     *
     * @return the value of user.userPhone
     *
     * @mbggenerated
     */
    public String getUserphone() {
        return userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userPhone
     *
     * @param userphone the value for user.userPhone
     *
     * @mbggenerated
     */
    public void setUserphone(String userphone) {
        this.userphone = userphone == null ? null : userphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userUnit
     *
     * @return the value of user.userUnit
     *
     * @mbggenerated
     */
    public String getUserunit() {
        return userunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userUnit
     *
     * @param userunit the value for user.userUnit
     *
     * @mbggenerated
     */
    public void setUserunit(String userunit) {
        this.userunit = userunit == null ? null : userunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.reviewStatus
     *
     * @return the value of user.reviewStatus
     *
     * @mbggenerated
     */
    public String getReviewstatus() {
        return reviewstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.reviewStatus
     *
     * @param reviewstatus the value for user.reviewStatus
     *
     * @mbggenerated
     */
    public void setReviewstatus(String reviewstatus) {
        this.reviewstatus = reviewstatus == null ? null : reviewstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.perissionInformation
     *
     * @return the value of user.perissionInformation
     *
     * @mbggenerated
     */
    public String getPerissioninformation() {
        return perissioninformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.perissionInformation
     *
     * @param perissioninformation the value for user.perissionInformation
     *
     * @mbggenerated
     */
    public void setPerissioninformation(String perissioninformation) {
        this.perissioninformation = perissioninformation == null ? null : perissioninformation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.joinDate
     *
     * @return the value of user.joinDate
     *
     * @mbggenerated
     */
    public Date getJoindate() {
        return joindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.joinDate
     *
     * @param joindate the value for user.joinDate
     *
     * @mbggenerated
     */
    public void setJoindate(Date joindate) {
        this.joindate = joindate;
    }
}